// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:7b0c22fd-af46-4517-85a2-2d4e223f0337',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'recipeapp-hosting-mobilehub-905809689',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd1yj6x1m9oiqy9.cloudfront.net',
aws_mobile_analytics_app_id : '640dacf0debb4ec3bd1afcc03b1aca29',
aws_project_id : '37890b1e-5496-4965-95da-16645ed28b24',
aws_project_name : 'RecipeApp',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'recipeapp-mobilehub-905809689',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});